

class Business(object):
    """Business data.

    Args:
        id (int): Unique serial id generated by the database (primary key).
        name (str): Name of business/organization.
    """
    def __init__(self, id, name):
        self.id = id
        self.name = name

    @classmethod
    def from_dict(cls, dct):
        """Instantiate class from a dictionary.

        Args:
            dct (dict): Seller information in the form of a dict.

        Returns: Business instance
        """
        return cls(
            id=dct['id'],
            name=dct['name']
        )

    def to_dict(self):
        """Construct dictionary of Business instance.

        Returns:
            dict: Business information in the form of a dict.
        """
        return {
            'id': self.id,
            'name': self.name
        }
